spring:
  application:
    name: quantum-file-ingester

  artemis:
    broker-url: tcp://${AMQ_HOST:localhost}:${AMQ_PORT:61616}
    user: ${AMQ_USER:admin}
    password: ${AMQ_PASSWORD:admin}

ingester:
  input-dir: ${INPUT_DIR:input}
  noop: ${FILE_NOOP:true}
  chunk-size: ${CHUNK_SIZE:10000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: file-ingester
    export:
      prometheus:
        enabled: true

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    com.quantum: INFO
    org.apache.camel: INFO
    org.apache.activemq: WARN
